<?php
namespace common\models;

use Yii;
use yii\db\ActiveRecord;

class UserSetting extends ActiveRecord
{
	const MAIL_OPERATOR_RESPONSE_REIVEW = 'MAIL_OPERATOR_RESPONSE_REIVEW';
	const NOTIFICATION_OPERATOR_RESPONSE_REIVEW = 'NOTIFICATION_OPERATOR_RESPONSE_REIVEW';
	const MAIL_NEW_PLAYER_REVIEW = 'MAIL_NEW_PLAYER_REVIEW';
	const NOTIFICATION_NEW_PLAYER_REVIEW = 'NOTIFICATION_NEW_PLAYER_REVIEW';

	const MAIL_OPERATOR_RESPONSE_COMPLAIN = 'MAIL_OPERATOR_RESPONSE_COMPLAIN';
	const NOTIFICATION_OPERATOR_RESPONSE_COMPLAIN = 'NOTIFICATION_OPERATOR_RESPONSE_COMPLAIN';
	const MAIL_NEW_PLAYER_COMPLAIN = 'MAIL_NEW_PLAYER_COMPLAIN';
	const NOTIFICATION_NEW_PLAYER_COMPLAIN = 'NOTIFICATION_NEW_PLAYER_COMPLAIN';

    public static function tableName()
    {
        return '{{%user_setting}}';
    }
}