<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All notifications have been deleted.' => 'All notifications have been deleted.',
    'All notifications have been marked as read.' => 'All notifications have been marked as read.',
    'Delete all' => 'Delete all',
    'Mark all as read' => 'Mark all as read',
    'Mark as read' => 'Mark as read',
    'Notifications' => 'Notifications',
    'Read' => 'Read',
    'There are no notifications to show' => 'There are no notifications to show',
    'View all' => 'View all',
    'a moment' => 'a moment',
    'ago' => 'ago',
    '{n, plural, one{one day} other{# days}}' => '{n, plural, one{one day} other{# days}}',
    '{n, plural, one{one hour} other{# hours}}' => '{n, plural, one{one hour} other{# hours}}',
    '{n, plural, one{one minute} other{# minutes}}' => '{n, plural, one{one minute} other{# minutes}}',
    '{n, plural, one{one month} other{# months}}' => '{n, plural, one{one month} other{# months}}',
    '{n, plural, one{one second} other{# seconds}}' => '{n, plural, one{one second} other{# seconds}}',
    '{n, plural, one{one week} other{# weeks}}' => '{n, plural, one{one week} other{# weeks}}',
    '{n, plural, one{one year} other{# years}}' => '{n, plural, one{one year} other{# years}}',
];
