<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All notifications have been deleted.' => 'Tất cả thông báo đã được xoá.',
    'All notifications have been marked as read.' => 'Tất cả thông báo đã được đánh dấu đã đọc.',
    'Delete all' => 'Xoá tất cả',
    'Mark all as read' => 'Đánh dấu tất cả đã đọc',
    'Mark as read' => 'Đánh dấu đã đọc',
    'Notifications' => 'Thông báo',
    'Read' => 'Đã đọc',
    'There are no notifications to show' => 'Không có thông báo nào',
    'View all' => 'Xem tất cả',
    'a moment' => 'Vừa tạo',
    'ago' => 'trước đây',
    '{n, plural, one{one day} other{# days}}' => '{n, plural, one{một ngày} other{# ngày}}',
    '{n, plural, one{one hour} other{# hours}}' => '{n, plural, one{một giờ} other{# giờ}}',
    '{n, plural, one{one minute} other{# minutes}}' => '{n, plural, one{một phút} other{# phút}}',
    '{n, plural, one{one month} other{# months}}' => '{n, plural, one{một tháng} other{# tháng}}',
    '{n, plural, one{one second} other{# seconds}}' => '{n, plural, one{một giây} other{# giây}}',
    '{n, plural, one{one week} other{# weeks}}' => '{n, plural, one{một tuần} other{# tuần}}',
    '{n, plural, one{one year} other{# years}}' => '{n, plural, one{một năm} other{# năm}}',
];
